import { getRecentTweets } from "@/lib/tweets";
import { twitterHandle } from "@/data/portfolio";
import SectionHeading from "@/components/SectionHeading";
import Reveal from "@/components/Reveal";
import TweetCarousel from "@/components/TweetCarousel";

export default async function TweetsSection() {
  const tweets = await getRecentTweets(3);

  if (tweets.length === 0) {
    return null;
  }

  return (
    <section id="tweets" className="scroll-mt-24 px-6 py-5">
      <div className="mx-auto max-w-5xl">
        <Reveal>
          <SectionHeading index="09" title="Recent Posts from X" />
          <p className="-mt-2 mb-6 max-w-xl text-sm text-muted">
            Auto-generated by my SOC/detection-engineering bot,{" "}
            <a
              href={`https://x.com/${twitterHandle}`}
              target="_blank"
              rel="noreferrer"
              className="text-accent hover:underline"
            >
              @{twitterHandle}
            </a>
            .
          </p>
          <TweetCarousel tweets={tweets} />
        </Reveal>
      </div>
    </section>
  );
}
